data_ingestion:
  test_size: 0.20
  random_state: 42

data_preprocessing:
  features: [ "review" ]
  target: "sentiment"

feature_engineering:
  max_features: 1000
  feature: "review"

model_training:
  target: "label"
  c: 10
  solver: "liblinear"
  penalty: "l2"
  max_iter: 1000
