data_ingestion:
  s3_dataset: "imdb.csv"
  test_size: 0.2
  random_state: 42

data_preprocessing:
  features: [ "review" ]
  target: "sentiment"

feature_engineering:
  max_features: 10000
  feature: "review"

model_training:
  target: "label"
  c: 1
  solver: "liblinear"
  penalty: "l1"
  max_iter: 10000
